services:
  - type: web
    name: BYU-MvcMovie
    env: dotnet
    plan: free
    rootDir: .
    buildCommand: "dotnet restore && dotnet build --configuration Release"
    preDeployCommand: "dotnet ef database update"
    startCommand: "dotnet run --configuration Release --urls=http://0.0.0.0:10000"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Data Source=MvcMovie.db"
